// Mocks generated by Mockito 5.4.4 from annotations
// in watchlist/test/presentation/pages/watchlist_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_series/tv_series.dart' as _i4;
import 'package:watchlist/watchlist.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWatchlistTvSeries_0 extends _i1.SmartFake
    implements _i2.GetWatchlistTvSeries {
  _FakeGetWatchlistTvSeries_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTvSeriesStatus_1 extends _i1.SmartFake
    implements _i2.GetWatchlistTvSeriesStatus {
  _FakeGetWatchlistTvSeriesStatus_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvSeries_2 extends _i1.SmartFake
    implements _i2.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvSeries_3 extends _i1.SmartFake
    implements _i2.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistTvSeriesState_4 extends _i1.SmartFake
    implements _i2.WatchlistTvSeriesState {
  _FakeWatchlistTvSeriesState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WatchlistTvSeriesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvSeriesCubit extends _i1.Mock
    implements _i2.WatchlistTvSeriesCubit {
  MockWatchlistTvSeriesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistTvSeries get getWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvSeries),
        returnValue: _FakeGetWatchlistTvSeries_0(
          this,
          Invocation.getter(#getWatchlistTvSeries),
        ),
      ) as _i2.GetWatchlistTvSeries);

  @override
  _i2.GetWatchlistTvSeriesStatus get getWatchlistTvSeriesStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvSeriesStatus),
        returnValue: _FakeGetWatchlistTvSeriesStatus_1(
          this,
          Invocation.getter(#getWatchlistTvSeriesStatus),
        ),
      ) as _i2.GetWatchlistTvSeriesStatus);

  @override
  _i2.SaveWatchlistTvSeries get saveWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistTvSeries),
        returnValue: _FakeSaveWatchlistTvSeries_2(
          this,
          Invocation.getter(#saveWatchlistTvSeries),
        ),
      ) as _i2.SaveWatchlistTvSeries);

  @override
  _i2.RemoveWatchlistTvSeries get removeWatchlistTvSeries =>
      (super.noSuchMethod(
        Invocation.getter(#removeWatchlistTvSeries),
        returnValue: _FakeRemoveWatchlistTvSeries_3(
          this,
          Invocation.getter(#removeWatchlistTvSeries),
        ),
      ) as _i2.RemoveWatchlistTvSeries);

  @override
  _i2.WatchlistTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWatchlistTvSeriesState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.WatchlistTvSeriesState);

  @override
  _i3.Stream<_i2.WatchlistTvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.WatchlistTvSeriesState>.empty(),
      ) as _i3.Stream<_i2.WatchlistTvSeriesState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void loadWatchlistTvSeriesStatus(int? id) => super.noSuchMethod(
        Invocation.method(
          #loadWatchlistTvSeriesStatus,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fetchWatchlistTvSeries() => super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistTvSeries,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWatchlistTvSeries(_i4.TvSeriesDetail? tvSeries) => super.noSuchMethod(
        Invocation.method(
          #addWatchlistTvSeries,
          [tvSeries],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteWatchlistTvSeries(int? id) => super.noSuchMethod(
        Invocation.method(
          #deleteWatchlistTvSeries,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.WatchlistTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i5.Change<_i2.WatchlistTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
